/**
 * build.mjs — assemble the single-file Codewright app.
 *
 *   node build.mjs            -> build/codewright.html
 *   node build.mjs --check    -> validate only, write nothing
 *
 * Inputs
 *   src/index.head.html   doctype, styles, theme bootstrap, <body> openers
 *   src/lang.js           language model, inference, completion, highlighting
 *   src/bundle.*.txt      the "@@ key" content bundle for the foundation tracks
 *   src/tracks.js         the TRACKS array
 *   src/engine.js         utilities, highlighter, markdown, editor, runners, store
 *   src/app.js            state, routing, every view
 *   catalog/_spine.json   the degree programme table
 *   catalog/<ID>.json     one emitted course per file
 */

import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const ROOT = dirname(fileURLToPath(import.meta.url));
const SRC = join(ROOT, 'src');
const CATALOG = join(ROOT, 'catalog');
const OUT_DIR = join(ROOT, 'build');
const OUT = join(OUT_DIR, 'codewright.html');
/* GitHub Pages serves ./docs straight from the default branch, so the published
   copy is written by the same build rather than kept in step by hand. */
const DOCS_DIR = join(ROOT, 'docs');
const DOCS_OUT = join(DOCS_DIR, 'index.html');

const checkOnly = process.argv.includes('--check');
const problems = [];
const notes = [];

const read = (p) => readFileSync(p, 'utf8');

/* ---------------------------------------------------------------- bundle */
const bundleParts = readdirSync(SRC)
  .filter((f) => /^bundle\.\d+\.txt$/.test(f))
  .sort((a, b) => Number(a.match(/\d+/)[0]) - Number(b.match(/\d+/)[0]));
if (!bundleParts.length) problems.push('no src/bundle.N.txt files found');
const bundleText = bundleParts.map((f) => read(join(SRC, f))).join('\n\n');

/* A raw </script would close the host <script type="text/plain"> tag early.
   The bundle deliberately writes them as <\/script ; parseBundle unescapes. */
if (/<\/script/i.test(bundleText)) {
  problems.push('bundle contains a raw </script — it must be written as <\\/script');
}
const bundleKeys = [...bundleText.matchAll(/^@@[ \t]+(\S+)[ \t]*$/gm)].map((m) => m[1]);
notes.push(`bundle: ${bundleParts.length} parts, ${bundleKeys.length} keys`);

/* ---------------------------------------------------------------- degree */
let degree = { program: null, courses: [] };
if (existsSync(join(CATALOG, '_spine.json'))) {
  const spine = JSON.parse(read(join(CATALOG, '_spine.json')));
  const order = spine.courses.map((c) => c.id);
  const byId = new Map(spine.courses.map((c) => [c.id, c]));

  const courses = [];
  const missing = [];
  for (const id of order) {
    const p = join(CATALOG, id + '.json');
    if (!existsSync(p)) { missing.push(id); continue; }
    const course = JSON.parse(read(p));

    /* the spine is the single source of truth for placement metadata */
    const s = byId.get(id);
    for (const key of ['title', 'year', 'level', 'credits', 'hours']) {
      if (String(course[key]) !== String(s[key])) {
        notes.push(`${id}: ${key} "${course[key]}" != spine "${s[key]}" — using the spine`);
        course[key] = s[key];
      }
    }
    course.prereqs = s.prereqs;
    course.stack = course.stack && course.stack.length ? course.stack : s.stack;
    course.icon = course.icon || s.icon;

    const labs = course.modules.filter((m) => m.lab).length;
    if (!labs) problems.push(`${id}: no labs`);
    courses.push(course);
  }
  if (missing.length) {
    notes.push(`catalog: ${missing.length} course(s) not yet authored -> ${missing.join(', ')}`);
  }
  degree = { program: spine.program, courses };
  notes.push(`degree: ${courses.length}/${order.length} courses bundled`);
} else {
  notes.push('catalog: no _spine.json — building without the degree');
}

/* `</script>` inside any JSON string would terminate the host <script>.
   Escaping every `<` as < keeps the JSON valid JS and inert to the parser. */
const degreeJson = JSON.stringify(degree).replace(/</g, '\\u003c');

/* ---------------------------------------------------------------- scripts */
const langJs = read(join(SRC, 'lang.js'));
const tracksJs = read(join(SRC, 'tracks.js'));
const engineJs = read(join(SRC, 'engine.js'));
const appJs = read(join(SRC, 'app.js'));

const appScript = [
  langJs,
  tracksJs,
  '\n/* ============ degree catalog (generated by build.mjs) ============ */\n',
  'const DEGREE_DATA = ' + degreeJson + ';\n',
  engineJs,
  appJs,
].join('\n');

/* The host page carries this script inline, so the HTML tokenizer sees it before
   the JS parser does. A literal `<!--` switches it into "script data escaped" state
   and a following literal `<script` into "double escaped", where `</script>` stops
   closing the tag — the script then swallows the rest of the document and nothing
   runs. Both parse fine as JavaScript, so `node --check` cannot see it. Spell the
   sequences out (`\x3c`, `'<\/scr' + 'ipt>'`) as the rest of the file does. */
for (const [seq, why] of [
  ['<' + '!--', 'starts an HTML comment inside the script — write it as <!\\x2d-'],
  ['<' + 'script', 'flips the tokenizer to double-escaped — write the tag name bare'],
  ['</' + 'script', 'closes the host tag early — write it as <\\/scr\' + \'ipt>'],
]) {
  if (appScript.includes(seq)) {
    const at = appScript.indexOf(seq);
    const line = appScript.slice(0, at).split('\n').length;
    problems.push(`assembled script contains a literal "${seq}" (line ~${line}) — it ${why}`);
  }
}

/* Syntax-check the assembled script before shipping it. */
if (!checkOnly || true) {
  const tmp = join(OUT_DIR, '.syntax-check.js');
  mkdirSync(OUT_DIR, { recursive: true });
  writeFileSync(tmp, appScript, 'utf8');
  try {
    execFileSync(process.execPath, ['--check', tmp], { stdio: 'pipe' });
    notes.push('syntax: assembled script parses cleanly');
  } catch (e) {
    problems.push('JavaScript syntax error in the assembled script:\n' +
      String(e.stderr || e.stdout || e.message).split('\n').slice(0, 12).join('\n'));
  } finally {
    try { rmSync(tmp, { force: true }); } catch {}
  }
}

/* ---------------------------------------------------------------- emit */
const head = read(join(SRC, 'index.head.html'));
const html = [
  head,
  '',
  '<script type="text/plain" id="bundle">',
  bundleText,
  '</' + 'script>',
  '',
  '<script>',
  appScript,
  '</' + 'script>',
  '</body>',
  '</html>',
  '',
].join('\n');

console.log('--- build report ---');
for (const n of notes) console.log('  ·', n);
if (problems.length) {
  console.log('\nPROBLEMS:');
  for (const p of problems) console.log('  !', p);
}

if (problems.length) {
  console.log('\nbuild aborted');
  process.exit(1);
}

if (checkOnly) {
  console.log('\ncheck passed (nothing written)');
  process.exit(0);
}

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(OUT, html, 'utf8');
mkdirSync(DOCS_DIR, { recursive: true });
writeFileSync(DOCS_OUT, html, 'utf8');
writeFileSync(join(DOCS_DIR, '.nojekyll'), '', 'utf8');
const kb = (Buffer.byteLength(html, 'utf8') / 1024).toFixed(0);
console.log(`\nwrote ${OUT}  (${kb} KB)`);
console.log(`wrote ${DOCS_OUT}  (this is what GitHub Pages serves)`);
