/**
 * store.mjs — accounts and progress on disk.
 *
 * One JSON file per user plus a small email index. No database, because the data is
 * tiny and a single file per account keeps the whole thing inspectable and trivially
 * backed up. Writes go through a temp file and a rename so an interrupted write can
 * never leave a half-written account behind, and every account's writes are
 * serialised on a per-id promise chain so two concurrent syncs cannot interleave.
 */

import { mkdir, readFile, writeFile, rename, readdir, unlink } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomUUID } from 'node:crypto';
import { hashToken, SESSION_TTL_MS } from './auth.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
export const DATA_DIR = process.env.CODEX_DATA_DIR || join(ROOT, 'data');
const USERS_DIR = join(DATA_DIR, 'users');
const INDEX_FILE = join(DATA_DIR, 'index.json');

let index = null;                 /* { emails: { <email>: <id> } } */
const chains = new Map();         /* id -> promise, serialising that user's writes */

async function ensureDirs() {
  await mkdir(USERS_DIR, { recursive: true });
}

async function writeAtomic(file, text) {
  const tmp = file + '.' + randomUUID().slice(0, 8) + '.tmp';
  await writeFile(tmp, text, 'utf8');
  try {
    await rename(tmp, file);
  } catch (e) {
    try { await unlink(tmp); } catch {}
    throw e;
  }
}

async function loadIndex() {
  if (index) return index;
  await ensureDirs();
  try {
    index = JSON.parse(await readFile(INDEX_FILE, 'utf8'));
    if (!index || typeof index !== 'object' || !index.emails) index = { emails: {} };
  } catch {
    index = { emails: {} };
    /* An index lost to a bad write is rebuildable — the accounts are the source of
       truth and each one carries its own email. */
    try {
      for (const f of await readdir(USERS_DIR)) {
        if (!f.endsWith('.json')) continue;
        try {
          const u = JSON.parse(await readFile(join(USERS_DIR, f), 'utf8'));
          if (u && u.email && u.id) index.emails[u.email] = u.id;
        } catch {}
      }
      if (Object.keys(index.emails).length) await writeAtomic(INDEX_FILE, JSON.stringify(index));
    } catch {}
  }
  return index;
}

async function saveIndex() {
  await writeAtomic(INDEX_FILE, JSON.stringify(index, null, 2));
}

function userFile(id) {
  /* ids are generated by randomUUID, but never let one reach the filesystem unchecked */
  if (!/^[0-9a-f-]{36}$/i.test(id)) throw new Error('bad user id');
  return join(USERS_DIR, id + '.json');
}

async function readUser(id) {
  try {
    return JSON.parse(await readFile(userFile(id), 'utf8'));
  } catch {
    return null;
  }
}

/* All mutations of one account run in order, so a sync and a session prune cannot
   overwrite each other's copy of the record. */
function withUser(id, fn) {
  const prev = chains.get(id) || Promise.resolve();
  const next = prev.then(fn, fn);
  chains.set(id, next.then(() => {}, () => {}));
  return next;
}

async function writeUser(user) {
  await ensureDirs();
  await writeAtomic(userFile(user.id), JSON.stringify(user, null, 2));
  return user;
}

export async function findByEmail(email) {
  const idx = await loadIndex();
  const id = idx.emails[email];
  return id ? readUser(id) : null;
}

export async function createUser(email, passwordHash) {
  const idx = await loadIndex();
  if (idx.emails[email]) return null;                 /* caller reports "already registered" */
  const user = {
    id: randomUUID(),
    email,
    passwordHash,
    createdAt: Date.now(),
    sessions: [],
    progress: null,
    rev: 0,
  };
  await writeUser(user);
  idx.emails[email] = user.id;
  await saveIndex();
  return user;
}

export function addSession(id, tokenHash, label) {
  return withUser(id, async () => {
    const user = await readUser(id);
    if (!user) return null;
    const now = Date.now();
    user.sessions = (user.sessions || [])
      .filter((s) => s.expires > now)
      .slice(-19);                                    /* keep the record small */
    user.sessions.push({ hash: tokenHash, created: now, expires: now + SESSION_TTL_MS, label: label || '' });
    await writeUser(user);
    return user;
  });
}

export async function findBySession(rawToken) {
  const hash = hashToken(rawToken);
  const idx = await loadIndex();
  const now = Date.now();
  for (const id of Object.values(idx.emails)) {
    const user = await readUser(id);
    if (!user || !user.sessions) continue;
    const s = user.sessions.find((x) => x.hash === hash);
    if (!s) continue;
    if (s.expires <= now) return null;
    return { user, session: s };
  }
  return null;
}

export function dropSession(id, rawToken) {
  const hash = hashToken(rawToken);
  return withUser(id, async () => {
    const user = await readUser(id);
    if (!user) return null;
    user.sessions = (user.sessions || []).filter((s) => s.hash !== hash);
    await writeUser(user);
    return user;
  });
}

/* `apply` receives the stored progress and returns the value to persist. Running it
   inside the chain is what makes a merge atomic against a concurrent sync. */
export function updateProgress(id, apply) {
  return withUser(id, async () => {
    const user = await readUser(id);
    if (!user) return null;
    user.progress = apply(user.progress);
    user.rev = (user.rev || 0) + 1;
    user.progressAt = Date.now();
    await writeUser(user);
    return user;
  });
}

export async function getUser(id) {
  return readUser(id);
}

export function publicUser(user) {
  return { id: user.id, email: user.email, createdAt: user.createdAt };
}
